version: '3.9'

services:
  db:
    image: postgres:16
    container_name: ambo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ambo_db
    ports:
      - "5432:5432"
    volumes:
      - ambo_pgdata:/var/lib/postgresql/data

  # api service can be added later once we build the image
  # api:
  #   build: .
  #   container_name: ambo-backend
  #   env_file:
  #     - .env
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - db

volumes:
  ambo_pgdata:
